sudo: required

services:
  - docker

install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build . -t marketreaction/sentiment-api
#  - docker build Dockerfile-arm -t marketreaction/sentiment-api:arm
  - docker push marketreaction/sentiment-api
#  - docker push marketreaction/sentiment-api:arm
